### PR TITLE
Recommend JSON merge-patch for patching resource properties

### PR DESCRIPTION
**Pull request by j5lim**
Currently [RPC](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#patch-resource) does not clearly specify how RPs need to implement PATCH operation (partial update of a resource). We would like to guide RPs to support JSON merge patch ([RFC 7396](https://tools.ietf.org/html/rfc7396)) so that we can have consistent behavior across RPs regarding PATCH operation on a resource.

### CODE REVIEW

**Review by pilor — APPROVED** [review]

**Comment by pilor** [comment]
Anthony and Gaurav are the only people I've seen that can merge

**Comment by j5lim** [comment]
@anthony-c-martin  @ravbhatnagar Could you help with merging this?

**Comment by pilor** [comment]
@anthony-c-martin @ravbhatnagar can you grant someone on the ARM API review team write access to this repo so they can approve PRs?

**Comment by anthony-c-martin** [comment]
@pilor I can merge but I can't assign permissions - I assum @ravbhatnagar would have to give admin on this repo.

**Pull request merged**
